# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField(verbose_name='Дата добавления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electro.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('feature1', models.CharField(blank=True, max_length=80, verbose_name='Характеристика 1')),
                ('feature2', models.CharField(blank=True, max_length=80, verbose_name='Характеристика 1')),
                ('feature3', models.CharField(blank=True, max_length=80, verbose_name='Характеристика 1')),
                ('feature4', models.CharField(blank=True, max_length=80, verbose_name='Характеристика 1')),
                ('feature5', models.CharField(blank=True, max_length=80, verbose_name='Характеристика 1')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electro.Category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electro.SubCategory'),
        ),
    ]
