# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0002_auto_20160705_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='case',
            field=models.CharField(blank=True, max_length=80, verbose_name='Тип корпуса'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, help_text='Цена '),
        ),
        migrations.AddField(
            model_name='product',
            name='value3',
            field=models.IntegerField(default=0, help_text='Только числовые значения'),
        ),
        migrations.AddField(
            model_name='product',
            name='value4',
            field=models.IntegerField(default=0, help_text='Только числовые значения'),
        ),
        migrations.AddField(
            model_name='product',
            name='value5',
            field=models.IntegerField(default=0, help_text='Только числовые значения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value1',
            field=models.CharField(blank=True, max_length=80, verbose_name='Только текстовое значение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value2',
            field=models.CharField(blank=True, max_length=80, verbose_name='Только текстовое значение'),
        ),
    ]
