# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0005_auto_20160706_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='value1',
            field=models.CharField(blank=True, help_text='Только строчные значения', max_length=80, verbose_name='Значение 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value2',
            field=models.CharField(blank=True, help_text='Только строчные значения', max_length=80, verbose_name='Значение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value3',
            field=models.IntegerField(default=0, help_text='Только числовые значения', verbose_name='Значение 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value4',
            field=models.IntegerField(default=0, help_text='Только числовые значения', verbose_name='Значение 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value5',
            field=models.IntegerField(default=0, help_text='Только числовые значения', verbose_name='Значение 5'),
        ),
    ]
