# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0006_auto_20160706_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value5',
        ),
        migrations.AddField(
            model_name='product',
            name='values',
            field=django.contrib.postgres.fields.jsonb.JSONField(default="'values':[],"),
        ),
    ]
