# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0008_auto_20160711_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='price',
            field=models.CharField(blank=True, default='Цена товара, Сом', max_length=80),
        ),
    ]
