# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0009_auto_20160712_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Название для таблицы'),
        ),
    ]
