# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0015_auto_20160712_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='values',
        ),
    ]
