# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 04:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electro', '0018_auto_20160714_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='values',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
