# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Category_geo',
        ),
        migrations.AlterField(
            model_name='geology',
            name='advanced_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geology',
            name='date',
            field=models.DateTimeField(verbose_name='published_date'),
        ),
    ]
