# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_category_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='geology',
            name='category_search',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Category_new'),
        ),
    ]
