# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_metal',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category_metal',
            name='image2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category_metal',
            name='image3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category_metal',
            name='image4',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category_metal',
            name='image5',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
