# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0003_auto_20160701_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metal',
            name='title',
        ),
    ]
