# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0004_remove_metal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_metal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
