# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metal', '0005_category_metal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_metal',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
